# https://freedium.cfd/https://blog.stackademic.com/building-a-smart-city-an-end-to-end-big-data-engineering-project-7a3d9a6ab104
# https://www.youtube.com/watch?v=Vv_fvwF41_0&ab_channel=CodeWithYu
version: '3'

services:
  zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        hostname: zookeeper
        container_name: zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
        healthcheck: 
        # to ensure the zookeeper is ready to accept connection before continuing
          test: ['CMD', 'bash', '-c', "echo 'Are you ok?' | nc localhost 2181"]
          interval: 10s
          timeout: 5s
          retries: 5

  broker:
    image: confluentinc/cp-server:7.4.0
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
      # if the healthcheck for zookeper is not healthy then kafka is not going to run
        condition: service_healthy
    ports:
      - "9092:9092" # Internal/external port
      - "9101:9101" # jmx
    environment:
      KAFKA_BROKER_ID: 1                                                                        # we have one kafka broker with ID 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'                                                 # 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT        #
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092      # ports where kafka will be listening
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter            # if you are not using confluence this is not needed
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                                 #
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - datamasterylab
    healthcheck:
      test: [ "CMD", "bash", "-c", 'nc -z localhost 9092' ]
      interval: 10s
      timeout: 5s
      retries: 5
        networks:
          - datamasterylab  